# Generated by Django 4.1.7 on 2023-06-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="QuestionAnswerKB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                ("answer", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WeiboContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blogger_name", models.CharField(max_length=256)),
                ("blogger_home", models.CharField(max_length=64)),
                ("weibo_content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WeiboContentIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blogger_keyword", models.CharField(max_length=256)),
                ("blogger_doclist", models.TextField()),
            ],
        ),
    ]
